### ISSUE TITLE
I cannot sync the wiki.

### ISSUE THREAD

**Issue by prosavage** [awact/wiki-action#7]
It appears it cannot read the password in the docker container.
![image](https://user-images.githubusercontent.com/29169519/68989579-83adef00-080e-11ea-813a-c0526ac398bf.png)

Here is the file. I am not sure what GH_PAT is, please tell me if anything is wrong.
```yml
name: Wiki Updater
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean updatePermissionsList
    - uses: awact/wiki-action@master
      env:
        ACTION_MAIL: naman0311@gmail.com
        ACTION_NAME: ProSavage
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: Wiki
        OWNER: illyria-io
        REPO_NAME: SkyblockX
```
