### ISSUE TITLE
Action does not ignore README.md

### ISSUE THREAD

**Issue by Andre601** [awact/wiki-action#9]
The GitHub Action does not ignore the README.md, even tho I set it under the `SKIP_MD` env variable.

My Workflow:
```yaml
name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Wiki
      uses: awact/wiki-action@master
      env:
        ACTION_MAIL: ${{ secrets.EMAIL }}
        ACTION_NAME: Andre601
        GH_PAT: ${{ secrets.GITHUB_PAT }}
        MD_FOLDER: wiki
        OWNER: Andre601
        REPO_NAME: PurrBot
        SKIP_MD: README.md
```
